drop table if exists items;
create table if not exists items (
                       id bigint generated by default as identity,
                       title varchar(255) not null,
                       content varchar(500) not null,
                       status varchar(10) not null,
                       primary key (id)
);